# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Generate settings.xml for Maven Buildsb0fa3aeaf105960f700e5cbc1df56fc934a
      uses: whelk-io/maven-settings-xml-action@v15
      with:
        mirrors: '[{ "id": "restletMirror", "mirrorOf": "maven-restlet*", "url": "https://maven.restlet.com" }]'
    - name: Build with Maven
      run: mvn -B -X clean install --file pom.xml
